[tool.poetry]
name = "froods"
version = "0.1.0"
description = ""
authors = ["Frank Rosner"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
openai = "^1.40.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
